// Run after adding new JSON files:  node generate-data.js
//
// Structure:
//   jsons/
//     <Cup Name>/          ← folder name becomes the cup label in the app
//       Match A - Match B.json
//       ...
//
// Each subfolder = one cup. Files inside = matches for that cup.

const fs   = require('fs');
const path = require('path');

const jsonsDir = path.join(__dirname, 'jsons');
const games    = [];

const entries = fs.readdirSync(jsonsDir, { withFileTypes: true });
const cupDirs = entries.filter(e => e.isDirectory()).sort((a, b) => a.name.localeCompare(b.name, 'sv'));

if (cupDirs.length === 0) {
  console.warn('No cup folders found inside jsons/. Create a subfolder named after the cup and put JSON files inside it.');
  process.exit(1);
}

for (const dir of cupDirs) {
  const cupName = dir.name;
  const cupPath = path.join(jsonsDir, cupName);
  const files   = fs.readdirSync(cupPath).filter(f => f.endsWith('.json')).sort((a, b) => a.localeCompare(b, 'sv'));

  console.log(`\n[${cupName}]`);
  for (const file of files) {
    const filePath = path.join(cupPath, file);
    try {
      const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
      games.push({ name: file.replace('.json', ''), cup: cupName, data });
      console.log(`  + ${file}`);
    } catch (err) {
      console.warn(`  SKIPPED (parse error): ${file} — ${err.message}`);
    }
  }
}

const output = `// Auto-generated by generate-data.js — do not edit manually\nwindow.GAME_DATA = ${JSON.stringify(games)};\n`;
fs.writeFileSync(path.join(jsonsDir, 'data.js'), output, 'utf8');
console.log(`\nDone! Bundled ${games.length} match(es) into jsons/data.js`);
